title:             Example Product Catalogue
email:             info@mapaction.org
description:       Discover how maps can help you make decisions in humanitarian response
author:            MapAction
baseurl:           /epc
url:               ""

# Social Profiles
twitter_username:  mapaction

facebook_username: mapaction

# Build settings
markdown:          kramdown
paginate:          5
paginate_path:     "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
